name: Terraform tfdocs
description: Validates a Terraform module
runs:
  using: composite
  steps:
    - name: Render terraform docs inside the README.md and push changes back to PR branch
      uses: terraform-docs/gh-actions@v0.8.0
      with:
        working-dir: .
        output-file: README.md
        output-method: inject
        git-push: "true"
        git-commit-message: "terraform-docs: automated action"
        config-file: ".tfdocs-config.yml"