name: Terraform tfdocs
description: Validates a Terraform module
inputs:
  tfdocs_config_path:
    default: ""
    description: "Path to the tfdocs config file"
    required: false
runs:
  using: composite
  steps:
    - name: Render terraform docs inside the README.md and push changes back to PR branch
      uses: terraform-docs/gh-actions@v0.8.0
      with:
        working-dir: .
        output-file: README.md
        output-method: inject
        git-push: "true"
        git-commit-message: "terraform-docs: automated action"
        config-file: ${{ inputs.tfdocs_config_path }}