name: first

on: push

jobs:
  job1:
    name: First Job
    runs-on: ubuntu-latest
    steps:
      - name: Setup helmfile
        uses: mamezou-tech/setup-helmfile@v0.9.0
        with:
          helmfile-version: ${{ steps.helm-versions.outputs.helmfile-version }}
          helm-version: ${{ steps.helm-versions.outputs.helm-version }}
          helm-diff-plugin-version: "v3.4.0"
          helm-s3-plugin-version: "0.10.0"
