name: Validate pull request
on:
  pull_request:
    paths-ignore:
      - ".github/workflows/release.yml"

jobs:
  validate:
    permissions:
      contents: write
      id-token: write
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
          token: ${{ secrets.ORG_GITHUB_TOKEN }}
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Checkout validate action
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.ORG_GITHUB_TOKEN }}
          ref: v1
          repository: HBOCodeLabs/action-terraform-module-validate
          path: ./.github/actions/validate
      - uses: ./.github/actions/validate
        with:
          github_token: ${{ secrets.ORG_GITHUB_TOKEN }}