name: Release module
on:
  push:
    paths-ignore:
      - "*.md"
      - ".github/CODEOWNERS"
      - ".github/METADATA.yaml"
      - ".github/workflows/**"
    branches:
      - "master"
jobs:
  release:
    permissions:
      contents: write
      id-token: write
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
          token: ${{ secrets.ORG_GITHUB_TOKEN }}
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0
      - name: Checkout validate action
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.ORG_GITHUB_TOKEN }}
          ref: v1
          repository: HBOCodeLabs/action-terraform-module-validate
          path: ./.github/actions/validate
      - uses: ./.github/actions/validate
        with:
          github_token: ${{ secrets.ORG_GITHUB_TOKEN }}
      - name: Generate semantic version
        id: generate-version
        uses: paulhatch/semantic-version@v4.0.2
        with:
          format: "${major}.${minor}.${patch}"
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ steps.generate-version.outputs.version_tag }}
          tag_name: ${{ steps.generate-version.outputs.version_tag }}